// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Movie struct {
	ID        string
	Name      string
	Year      sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

type Review struct {
	ID        string
	UserID    string
	MovieID   string
	Rating    sql.NullInt64
	Review    sql.NullString
	CreatedAt interface{}
	UpdatedAt interface{}
}

type User struct {
	ID        string
	Name      string
	CreatedAt interface{}
	UpdatedAt interface{}
}
